### ISSUE TITLE
Hi i have this issue

### ISSUE THREAD

**Issue by HugoLifes** [federicodesia/custom_timer#5]
The error it gives me is the difference> = 1 but I have done everything to solve it, any advice you can give me? The only thing I did was a function to get the difference of a current date and an expiration date and make it count to zero and it's all but seconds before finishing I get the error of form.duration - to.duration> = 1 no I did nothing of the other world, and even tried to stop the counter seconds before but this error does not appear before reaching 00:00:00

This is a simple counter timer i used
![error_dif](https://user-images.githubusercontent.com/22489848/120378394-9ba76f80-c2db-11eb-9c24-8a6911709c21.png)

this is my function to get the diff between to dates and next try to count to 0
![funcion](https://user-images.githubusercontent.com/22489848/120378479-b974d480-c2db-11eb-94a3-5bbad8de09fb.png)

this is the simple counter timer full view
![full_method](https://user-images.githubusercontent.com/22489848/120379000-5df71680-c2dc-11eb-9fc8-f3e7727b602f.png)

**Comment by federicodesia** [comment]
Hi! This can happen because you are using the onFinishAction property incorrectly. This property receives a CustomTimerAction.



<h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CustomTimerAction actions:</h3>
Actions | Description
-- | --
CustomTimerAction.go_to_start | Shows the start of the timer.
CustomTimerAction.go_to_end | Shows the end of the timer.
CustomTimerAction.auto_start | Automatically starts the timer.




If you don't get what you want, you can implement a custom method using the onFinish callback function.

These two possibilities are documented in more detail in the README file.
If the error persists, please share your code in text format and the exception you get in the console.

I hope I have helped you and that the package is useful for you!
